# Generated by Django 6.0.6 on 2026-07-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('preparation_method', models.CharField(blank=True, max_length=80)),
                ('serving_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('serving_unit', models.CharField(max_length=40)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('source', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'preparation_method'],
            },
        ),
    ]
