# Generated by Django 6.0.6 on 2026-07-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], default='other', max_length=20)),
                ('original_text', models.TextField()),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('uncertainty', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('preparation_method', models.CharField(blank=True, max_length=80)),
                ('estimated_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('uncertainty', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=240)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.meal')),
                ('nutrition_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.nutritionitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('corrected_calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='meals.mealitem')),
            ],
        ),
    ]
