# Generated by Django 6.0.6 on 2026-07-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('restrictions_applied', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-target_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=40)),
                ('preparation_method', models.CharField(blank=True, max_length=80)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rationale', models.TextField(blank=True)),
                ('nutrition_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.nutritionitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.mealplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
